### ISSUE TITLE
Model changes proposal/questions

### ISSUE THREAD

**Issue by algodave** [menro/NewTech#69]
After the new mockups on [invision](http://invis.io/8B387XD3A) me and @safeforge had a brainstorming session; we see the following main changes - please review

+ Abstract the **Location** concept, currently wrapped into Company, in order to reuse it for other entities (such as Event, see later points)

+ **Project** is a new concept to be modeled. We are thinking to attach it to a Company with a `belongs_to` relationship

+ **Topics** is a new concept to represent items in the bottom left box over the map (Technology, Natural Food, etc.). It's associated with all the main entities: Company, Job, Event, Project. What about News?

+ **Event** is a new entity, it's geo-referenced through a `belongs_to` relationship with the Location concept

Questions/thoughts:

1. About the *Follow* feature, consider this use case. I want to follow all "Technology" activities from United States, except from New York; and I want to follow "Natural Foods" activities only from Boulder. Is your idea something like this?

**Comment by menro** [comment]
Overall sounds right
Minor change: topics to industry

Question:
People?

Project, Job, and Event should be attached to person or company

Freelance should be attached to person

As far as following yes, but i do not see an easy UI for handling your technology use case. the except NY. I think the process is bit more manual. 

Im also a little concerned that people will follow things that are 2 large World, Country instead of zip code, county, state and I might suggest we do not allow following at the world or country level only state and below. thoughts?

**Comment by algodave** [comment]
I was thinking the same thing as not allowing users to follow areas larger
than state, doing that might overwhelm a user with too much notifications.

Will think about other things tomorrow, I'm from mobile now, going to sleep
Il 18/giu/2015 18:30, "Robert Reich" <notifications@github.com> ha scritto:
